version: "3.1"

services:
  db:
    image: postgres:13.0
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - chat

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
    networks:
      - chat

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - ${MINIO_PORT}:${MINIO_PORT}
      - ${MINIO_PORT_CONSOLE}:${MINIO_PORT_CONSOLE}
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESSKEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRETKEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - chat

volumes:
  postgres:
  minio_data:

networks:
  chat:
